//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::DanielLochner.Assets.MinMax))]
	public class PropertyProvider_DanielLochner_Assets_MinMax : Unity.VisualScripting.SerializedPropertyProvider<DanielLochner.Assets.MinMax>
	{
	}
}
